apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    {{- if eq .Values.service.targetPort "" }}
    targetPort: {{ .Values.service.port }}
    {{- else}}
    targetPort: {{.Values.service.targetPort}}
    {{- end}}
  selector:
    app: techtrends
    tag: techtrends
  type: {{ .Values.service.type }} 
