apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    # {{- if  .Values.service.targetPort == 0 }}
    # targetPort: {{ .Values.service.port }}
    # {{- else}}
    # targetPort: {{.Values.service.targetPort}}
    # {{- end}}
    targetPort: {{.Values.service.targetPort | default .Values.service.port}}
  selector:
    app: techtrends
    tag: techtrends
  type: {{ .Values.service.type }} 
