apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{default .Values.service.port .Values.service.targetPort }}
  selector:
    app: techtrends
    tag: techtrends
  type: {{ .Values.service.type }} 
